# Interval setting
# discriminator_train_start_steps: 0    # Number of steps to start to train discriminator.
train_max_steps: 50000               # Number of pre-training steps.
save_interval_steps: 2000           # Interval steps to save checkpoint.
eval_interval_steps: 1000             # Interval steps to evaluate the network.
log_interval_steps: 2000              # Interval steps to record the training log.
resume:                               # Epoch to resume training.

# Loss balancing coefficients.
lambda_reconstruct: 1  # TODO: pianoroll conditioning

# Mel-spectral loss setting
reconstruct_loss:
  _target_: tp_pt_vae.losses.PianorollDistanceLoss
  loss_type: bce

# kld loss setting
kld_loss:
  _target_: tp_pt_vae.losses.KLDivergenceLoss

# Feature matching loss setting
# fm_loss:
#   _target_: sifigan.losses.FeatureMatchLoss
#   average_by_layers: false  # Whether to average loss by #layers in each discriminator.

# Optimizer and scheduler setting
vae_optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
  betas: [0.5, 0.9]
  weight_decay: 0.0

# Sampling
sample_grid: [8, 8]
save_array_samples: true
save_image_samples: true
save_pianoroll_samples: true
midi:
  lowest_pitch: 24 # the lowest pitch of the piano-rolls
  programs: [0, 0, 25, 33, 48]
  is_drums: [1, 0, 0, 0, 0]
  tempo: 100 # in bpm
colormap:
  - [1., 0., 0.]
  - [1., .5, 0.]
  - [0., 1., 0.]
  - [0., 0., 1.]
  - [0., .5, 1.]
