# @package _global_

defaults:
  - _self_
  - generator: musegan
  - data: lpd_small

hydra:
  run:
    dir: ./
  output_subdir: null
  job_logging:
    formatters:
      simple:
        format: '[%(asctime)s][%(levelname)s][%(module)s | %(lineno)s] %(message)s'
    disable_existing_loggers: false

out_dir: out/debug_gp                 # Directory to output decoding results.
checkpoint_path:          # Path to the checkpoint of pre-trained model.
checkpoint_steps: 400000  # Path to the checkpoint of pre-trained model.
seed: 100                 # Seed number for random numbers.
save_source: false        # Whether to save source excitation signals.
sample_grid: [8, 8]
sf2_path: ./font.sf2  # $ sudo apt install fluidsynth && cp /usr/share/sounds/sf2/FluidR3_GM.sf2 ./font.sf2
